input {
  syslog {
    port => 514
    ecs_compatibility => "v8"
  }
}

filter {
  if [syslog5424_pri] or [priority] {
    mutate {
      add_field => { "[event][dataset]" => "edge.syslog" }
    }
  }

  if [program] == "nginx_access" or [syslog_program] == "nginx_access" {
    json {
      source => "message"
      target => "nginx"
      tag_on_failure => ["_nginx_json_parse_failure"]
    }
    mutate {
      add_field => { "[event][dataset]" => "nginx.access" }
    }
  } else if [program] == "nginx_error" or [syslog_program] == "nginx_error" {
    mutate {
      add_field => { "[event][dataset]" => "nginx.error" }
    }
  } else {
    mutate {
      add_field => { "[event][dataset]" => "haproxy.traffic" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "shlb-forensics-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
}
